plugins {
    id "com.android.application"
}

android {
    namespace "com.kersorus.timecalendar"
    compileSdk 35

    defaultConfig {
        applicationId "com.kersorus.timecalendar"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "0.2"

        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
}
