plugins {
    id "com.android.application"
}

android {
    namespace "com.kersorus.timecalendar"
    compileSdk 35
    flavorDimensions "target"

    defaultConfig {
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName "0.6.3"

        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
    }

    productFlavors {
        timecalendar {
            dimension "target"
            applicationId "com.kersorus.timecalendar"
        }

        warehouse {
            dimension "target"
            applicationId "com.kersorus.warehousepay"
            versionCode 8
            versionName "0.7.0"
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
}
