const KEY='las_salary_pwa_v1';
const defaults={settings:{basePickPrice:6.1,shiftHours:10.75,hourlyRate:147,taxPercent:13},schedule:{pattern:'',anchorDate:''},shifts:{}};
let state=load(), visible=new Date(new Date().getFullYear(),new Date().getMonth(),1), mode='normal', pendingPattern='', activeKey='', deferredPrompt=null, dragX=null;
const $=id=>document.getElementById(id);
function merge(x){return{settings:{...defaults.settings,...(x?.settings||{})},schedule:{...defaults.schedule,...(x?.schedule||{})},shifts:x?.shifts&&typeof x.shifts==='object'?x.shifts:{}}}
function load(){try{return merge(JSON.parse(localStorage.getItem(KEY)))}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function key(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function date(k){const[y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)}
function day(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function diff(a,b){return Math.round((day(b)-day(a))/86400000)}
function mod(x,n){return((x%n)+n)%n}
function scheduled(d){const{pattern,anchorDate}=state.schedule;if(!pattern||!anchorDate)return false;const delta=diff(date(anchorDate),d);if(pattern==='5/2')return mod(delta,7)<5;const work=pattern==='2/2'?2:pattern==='3/3'?3:0;return work?mod(delta,work*2)<work:false}
function picks(s={}){return['cancel','accept','returns','issue','reject','payment','repack'].reduce((n,k)=>n+Number(s[k]||0),0)}
function workday(d){const s=state.shifts[key(d)];if(s?.override===1||picks(s)>0)return true;if(s?.override===0)return false;return scheduled(d)}
function net(s={}){const p=state.settings.basePickPrice*(Number(s.cancel||0)*.6+Number(s.accept||0)*.8+Number(s.returns||0)*.9+Number(s.issue||0)*1.1+Number(s.reject||0)*1.1+Number(s.payment||0)*1.1+Number(s.repack||0)*1.3);const shift=picks(s)>0?state.settings.shiftHours*state.settings.hourlyRate:0;return(p+shift)*(1-state.settings.taxPercent/100)}
function color(d){const first=d.getDate()<=15,even=(d.getMonth()+1)%2===0;return even?(first?'#4270a8':'#cd6937'):(first?'#4c8c54':'#7f5696')}
function render(){renderTitle();renderMode();renderCalendar();renderPayments()}
function renderTitle(){$('monthTitle').textContent=visible.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}
function renderMode(){$('modeHint').textContent=mode==='add'?'Нажмите дату, чтобы добавить смену':mode==='remove'?'Нажмите дату, чтобы убрать смену':state.schedule.pattern?`График ${state.schedule.pattern}`:'График не выбран'}
function renderCalendar(){const cal=$('calendar');cal.innerHTML='';['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].forEach(n=>{const x=document.createElement('div');x.className='weekday';x.textContent=n;cal.append(x)});const first=new Date(visible.getFullYear(),visible.getMonth(),1),offset=(first.getDay()+6)%7,len=new Date(visible.getFullYear(),visible.getMonth()+1,0).getDate(),today=key(new Date());for(let i=0;i<42;i++){const n=i-offset+1,b=document.createElement('button');b.className='day';if(n<1||n>len){b.disabled=true;b.style.visibility='hidden';cal.append(b);continue}const d=new Date(visible.getFullYear(),visible.getMonth(),n),k=key(d),s=state.shifts[k],v=s?net(s):0;b.textContent=`${n}${v>0?`\n${Math.round(v)}₽`:''}`;if(workday(d)){b.classList.add('work');b.style.background=color(d)}if(v>=5000)b.classList.add('good');if(k===today)b.classList.add('today');b.onclick=()=>clickDate(d);cal.append(b)}}
function clickDate(d){const k=key(d);if(mode==='add'){state.shifts[k]={...(state.shifts[k]||{}),override:1};mode='normal';save();render();return}if(mode==='remove'){state.shifts[k]={...(state.shifts[k]||{}),override:0};mode='normal';save();render();return}if(!workday(d)){alert('Сначала добавьте смену через меню «График».');return}activeKey=k;const s=state.shifts[k]||{override:1};$('shiftDateTitle').textContent=d.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});[['cancelCount','cancel'],['acceptCount','accept'],['returnCount','returns'],['issueCount','issue'],['rejectCount','reject'],['paymentCount','payment'],['repackCount','repack']].forEach(([id,n])=>$(id).value=s[n]||'');preview();$('shiftDialog').showModal()}
function fromDialog(){return{...(state.shifts[activeKey]||{}),override:1,cancel:+$('cancelCount').value||0,accept:+$('acceptCount').value||0,returns:+$('returnCount').value||0,issue:+$('issueCount').value||0,reject:+$('rejectCount').value||0,payment:+$('paymentCount').value||0,repack:+$('repackCount').value||0}}
function preview(){$('shiftPreview').textContent=`Чистыми: ${Math.round(net(fromDialog()))} ₽`}
function periods(start,count){const out=[];for(let i=0;i<count;i++){const m=new Date(start.getFullYear(),start.getMonth()+i,1),y=m.getFullYear(),mo=m.getMonth();out.push({pay:new Date(y,mo,25),from:new Date(y,mo,1),to:new Date(y,mo,15),color:color(new Date(y,mo,1))});out.push({pay:new Date(y,mo+1,10),from:new Date(y,mo,16),to:new Date(y,mo+1,0),color:color(new Date(y,mo,16))})}return out.sort((a,b)=>a.pay-b.pay)}
function total(p){let sum=0;for(const[k,s]of Object.entries(state.shifts)){const d=date(k);if(d>=day(p.from)&&d<=day(p.to))sum+=net(s)}return sum}
function fmt(d){return d.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}
function short(d){return d.toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}
function upcoming(n=2){const t=day(new Date());return periods(new Date(t.getFullYear(),t.getMonth()-2,1),8).filter(p=>day(p.pay)>=t).slice(0,n)}
function renderPayments(){const box=$('payments');box.innerHTML='';upcoming().forEach((p,i)=>{const b=document.createElement('button');b.className='payment-card';b.style.setProperty('--accent',p.color);b.innerHTML=`<span>${i?'Следующая':'Ближайшая'}</span><b>${fmt(p.pay)}</b><strong>${Math.round(total(p))} ₽</strong><small>${short(p.from)}–${short(p.to)}</small>`;b.onclick=showPayments;box.append(b)})}
function showPayments(){const now=new Date(),all=periods(new Date(now.getFullYear(),now.getMonth()-12,1),25);$('paymentsList').innerHTML=all.map(p=>`<div class="payment-card" style="--accent:${p.color};margin-bottom:8px"><b>${fmt(p.pay)}</b><strong>${Math.round(total(p))} ₽</strong><small>${short(p.from)}–${short(p.to)}</small></div>`).join('');$('menuDialog').close();$('paymentsDialog').showModal()}
function exportJson(){const blob=new Blob([JSON.stringify({format:'LaSalaryBackup',version:1,exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`las-backup-${key(new Date())}.json`;a.click();URL.revokeObjectURL(u)}
async function importJson(file){const p=JSON.parse(await file.text());if(p?.format!=='LaSalaryBackup'||!p.data)throw new Error('Неверный формат резервной копии');if(!confirm('Заменить текущие данные импортированными?'))return;state=merge(p.data);save();render()}
function move(n){visible=new Date(visible.getFullYear(),visible.getMonth()+n,1);render()}
$('prevMonth').onclick=()=>move(-1);$('nextMonth').onclick=()=>move(1);$('todayButton').onclick=()=>{const n=new Date();visible=new Date(n.getFullYear(),n.getMonth(),1);render()};$('monthTitle').onclick=()=>{const v=prompt('Введите месяц в формате ГГГГ-ММ',`${visible.getFullYear()}-${String(visible.getMonth()+1).padStart(2,'0')}`);if(/^\d{4}-\d{2}$/.test(v||'')){const[y,m]=v.split('-').map(Number);if(m>=1&&m<=12){visible=new Date(y,m-1,1);render()}}};$('menuButton').onclick=()=>$('menuDialog').showModal();$('scheduleButton').onclick=()=>$('scheduleDialog').showModal();$('settingsButton').onclick=()=>{$('menuDialog').close();['basePickPrice','shiftHours','hourlyRate','taxPercent'].forEach(k=>$(k).value=state.settings[k]);$('settingsDialog').showModal()};$('allPaymentsButton').onclick=showPayments;$('exportButton').onclick=exportJson;$('importInput').onchange=async e=>{try{if(e.target.files[0])await importJson(e.target.files[0])}catch(x){alert(x.message)}finally{e.target.value='';$('menuDialog').close()}};document.querySelectorAll('[data-pattern]').forEach(b=>b.onclick=()=>{pendingPattern=b.dataset.pattern;$('anchorDate').value=key(new Date());$('scheduleDialog').close();$('anchorDialog').showModal()});$('savePatternButton').onclick=()=>{if(!$('anchorDate').value)return;state.schedule={pattern:pendingPattern,anchorDate:$('anchorDate').value};mode='normal';save();$('anchorDialog').close();render()};$('addShiftMode').onclick=()=>{mode='add';$('scheduleDialog').close();render()};$('removeShiftMode').onclick=()=>{mode='remove';$('scheduleDialog').close();render()};['cancelCount','acceptCount','returnCount','issueCount','rejectCount','paymentCount','repackCount'].forEach(id=>$(id).oninput=preview);$('saveShiftButton').onclick=()=>{state.shifts[activeKey]=fromDialog();save();$('shiftDialog').close();render()};$('saveSettingsButton').onclick=()=>{state.settings={basePickPrice:+$('basePickPrice').value||6.1,shiftHours:+$('shiftHours').value||10.75,hourlyRate:+$('hourlyRate').value||147,taxPercent:+$('taxPercent').value||13};save();$('settingsDialog').close();render()};$('calendar').addEventListener('pointerdown',e=>dragX=e.clientX);$('calendar').addEventListener('pointerup',e=>{if(dragX===null)return;const dx=e.clientX-dragX;dragX=null;if(Math.abs(dx)>55)move(dx<0?1:-1)});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installButton').hidden=false});$('installButton').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installButton').hidden=true};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
